### ISSUE TITLE
Master control data anomaly

### ISSUE THREAD

**Issue by djisb** [jezzab/DUMLdore#27]
I use the Backup Tool V2.12 to Rollback 1.03.7000, and the master data exception will be displayed
![2](https://user-images.githubusercontent.com/34053349/35381076-129ba4bc-01f6-11e8-9a72-f0d9401fb7e9.png)
can u tell me why？
But 1.03.1000 its normal，My mavic pro factory firmware its 1.03.1000

**Comment by jezzab** [comment]
http://dji.retroroms.info/howto/recorder-sdcard-fix

On 25 Jan. 2018 8:37 pm, "djisb" <notifications@github.com> wrote:

I use the Backup Tool V2.12 to Rollback 1.03.7000, and the master data
exception will be displayed
[image: 2]
<https://user-images.githubusercontent.com/34053349/35381076-129ba4bc-01f6-11e8-9a72-f0d9401fb7e9.png>
can u tell me why？
But 1.03.1000 its normal，My mavic pro factory firmware its 1.03.1000

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jezzab/DUMLdore/issues/27>, or mute the thread

**Comment by djisb** [comment]
and below FW1.03.10000 ，Master control data anomaly

**Comment by djisb** [comment]
thank you very much
